[project]
name = "ftk"
version = "0.1.0"
authors = [{name="Ana", email="magui.lopes03@gmail.com"}]
dependencies = ["jjcli"]
description = """ """
license = {text = "MIT"}

[project.scripts]
ftl-occ = "ftk.base:main"